export enum ActionTypes {
	MOVE_CELL = 'MOVE_CELL',
	DELETE_CELL = 'DELETE_CELL',
	UPDATE_CELL = 'UPDATE_CELL',
	INSERT_CELL_AFTER = 'INSERT_CELL_AFTER',

	BUNDLE_START = 'BUNDLE_START',
	BUNDLE_COMPLETE = 'BUNDLE_COMPLETE',
}
